### ISSUE TITLE
Go through and pipeclean README

### ISSUE THREAD

**Issue by weiya711** [SparseRooflineBenchmark/SparseRooflineBenchmark#18]

**Comment by weiya711** [comment]
I had issues running `src/generate.jl` with the Comonicon package. 
Running the following commands fixed it. 
```bash
% julia 
% julia> import Pkg; Pkg.add("Comonicon")
```

**Comment by willow-ahrens** [comment]
Oh, I see. I think we should add comonicon to the package deps so it downloads automatically

**Comment by willow-ahrens** [comment]
This file appears to be missing an entry for it: https://github.com/SparseRooflineBenchmark/SparseRooflineBenchmark/blob/main/src/Project.toml

**Comment by weiya711** [comment]
Ok let me push the fix before merging this PR

**Comment by weiya711** [comment]
Ok this should be resolved now. @willow-ahrens can you take another look?
