### ISSUE TITLE
Add uniform random distribution generator to the SpMV problem generator

### ISSUE THREAD

**Issue by weiya711** [SparseRooflineBenchmark/SparseRooflineBenchmark#27]
This issue follows the guidelines in #16 and is one of the tasks from #2. 

The generator would generate a set of sparse A matrices from a uniform distribution and some random x, and request y=Ax. We decided to have this explicitly be separate from the RMAT generator (even though it is a special case of RMAT).

Some arguments used to set the generator include:

1. Random seed
2. The uncompressed size (dimensions) of the matrix
3. The sparsity of the matrix

**Comment by gdinh** [comment]
Clarified during meeting: "uniform random" distribution = Erdos-Renyi

**Comment by willow-ahrens** [comment]
This is fixed!
